name = "my-app"
compatibility_date = "2024-05-01"
main = ".vercel/output/functions/_worker.js"

[build]
command = "npm run build"

[env.production]
# Add your environment variables here or set them in the Cloudflare dashboard
# DATABASE_URL = "your-production-database-url"
# JWT_SECRET = "your-jwt-secret"
# FRONTEND_URL = "your-frontend-url"

[site]
bucket = ".vercel/output/static" 